# Generated by Django 3.0.7 on 2020-06-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20200629_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='adult_status',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='post',
            name='domain',
            field=models.TextField(default=''),
        ),
    ]
