# Generated by Django 3.0.7 on 2020-06-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20200629_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='regist_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
