# Generated by Django 3.0.7 on 2020-06-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_post_regist_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='end_date',
        ),
        migrations.AddField(
            model_name='post',
            name='do_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='do_week',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='recruit_company',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='recruit_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='recurit_member',
            field=models.IntegerField(default=0),
        ),
    ]
