# Generated by Django 3.0.7 on 2020-06-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_post_do_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='adult_status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
