# Generated by Django 3.0.7 on 2020-06-29 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0009_post_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='recurit_member',
            new_name='recruit_member',
        ),
    ]
