# Generated by Django 3.0.7 on 2020-06-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0011_auto_20200629_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.TextField(default='https://www.1365.go.kr/vols/1572247904127/partcptn/timeCptn.do', max_length=500),
        ),
    ]
