# Generated by Django 3.0.7 on 2020-07-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0013_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='site_domain',
            field=models.IntegerField(default=1),
        ),
    ]
