# Generated by Django 3.0.7 on 2020-07-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0014_post_site_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='do_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='do_week',
        ),
        migrations.AlterField(
            model_name='post',
            name='adult_status',
            field=models.BooleanField(default=True),
        ),
    ]
