# Generated by Django 3.0.7 on 2020-07-01 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0015_auto_20200701_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='recruit_date',
            new_name='do_date_extra',
        ),
    ]
