# Generated by Django 3.0.8 on 2020-08-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0018_post_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinds', models.CharField(default='', max_length=10)),
                ('li', models.CharField(default='', max_length=5)),
            ],
        ),
    ]
